[profile.default]
# @see {@link https://github.com/foundry-rs/foundry/issues/4060}
auto_detect_remappings = false
bytecode_hash = "none"
cbor_metadata = false
sparse_mode = false

src = 'src'
out = 'out'
libs = [ 'lib' ] # See more config options https://github.com/foundry-rs/foundry/tree/master/config
viaIR = true
allow_paths = ['../../node_modules', '../../node_modules/@zk-email/contracts', '../../node_modules/@ethereum-attestation-service/eas-contracts/contracts']
solc_version = '0.8.21'

[profile.default.optimizer_details]
# constantOptimizer = true
yul = true
